using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using System.Numerics;

namespace Content.Client.MainMenu.UI;

[GenerateTypedNameReferences]
public sealed partial class MainMenuControl : Control
{
    public const string StyleIdentifierMainMenu = "mainMenu";
    public const string StyleIdentifierMainMenuVBox = "mainMenuVBox";
    private const float ConnectingProgressMinimum = 0.18f;
    private const float ConnectingProgressMaximum = 0.9f;

    private static readonly Color HoverTextColor = Color.FromHex("#DDFEFF");
    private static readonly Color PressTextColor = Color.FromHex("#9CF8FF");

    private readonly TextureResource _inactivePanelTexture;
    private readonly TextureResource _activePanelTexture;
    private readonly MenuPanelVisual[] _menuPanels;
    private float _animationTime;
    private Vector2 _backgroundOffset;
    private bool _directConnectForcedActive;

    public MainMenuControl(IResourceCache resCache, IConfigurationManager configMan)
    {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(Background, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(ConnectingOverlay, LayoutContainer.LayoutPreset.Wide);

        LayoutContainer.SetAnchorPreset(VBox, LayoutContainer.LayoutPreset.TopRight);
        LayoutContainer.SetMarginRight(VBox, -25);
        LayoutContainer.SetMarginTop(VBox, 30);
        LayoutContainer.SetGrowHorizontal(VBox, LayoutContainer.GrowDirection.Begin);

        var logoTexture = resCache.GetResource<TextureResource>("/Textures/Logo/logo.png");
        Logo.Texture = logoTexture;

        _inactivePanelTexture = resCache.GetResource<TextureResource>("/Textures/UI/Panel_MM.png");
        _activePanelTexture = resCache.GetResource<TextureResource>("/Textures/UI/Panel_MM_Active.png");

        var currentUserName = configMan.GetCVar(CVars.PlayerName);
        UsernameBox.Text = currentUserName;

        _menuPanels =
        [
            new MenuPanelVisual(DirectConnectButton, DirectConnectPanel),
            new MenuPanelVisual(OptionsButton, OptionsPanel),
            new MenuPanelVisual(QuitButton, QuitPanel),
            new MenuPanelVisual(ChangelogButton, ChangelogPanel),
        ];
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _animationTime += (float) args.DeltaSeconds;

        var targetOffset = new Vector2(
            MathF.Sin(_animationTime * 0.05f) * 10f,
            MathF.Cos(_animationTime * 0.035f) * 6f);

        var smoothing = 1f - MathF.Exp(-3.5f * (float) args.DeltaSeconds);
        _backgroundOffset = Vector2.Lerp(_backgroundOffset, targetOffset, smoothing);

        Background.Margin = new Thickness(
            -48f + _backgroundOffset.X,
            -32f + _backgroundOffset.Y,
            -48f - _backgroundOffset.X,
            -32f - _backgroundOffset.Y);

        UpdateConnectingOverlay();
        UpdateMenuPanelEffects();
    }

    public void SetConnectingState(bool connecting, string? address = null)
    {
        _directConnectForcedActive = connecting;
        ConnectingOverlay.Visible = connecting;
        ConnectingAddress.Visible = !string.IsNullOrWhiteSpace(address);
        ConnectingAddress.Text = string.IsNullOrWhiteSpace(address)
            ? string.Empty
            : Loc.GetString("main-menu-connecting-address", ("address", address));

        if (!connecting)
            ConnectingProgressBar.Value = ConnectingProgressMinimum;
    }

    private void UpdateConnectingOverlay()
    {
        if (!ConnectingOverlay.Visible)
            return;

        var cycle = (_animationTime * 0.85f) % 1f;
        var wave = cycle < 0.5f
            ? cycle * 2f
            : (1f - cycle) * 2f;

        ConnectingProgressBar.Value = MathHelper.Lerp(
            ConnectingProgressMinimum,
            ConnectingProgressMaximum,
            wave);
    }

    private void UpdateMenuPanelEffects()
    {
        foreach (var panel in _menuPanels)
        {
            var drawMode = panel.Button.DrawMode;
            var active = ReferenceEquals(panel.Button, DirectConnectButton) && _directConnectForcedActive ||
                drawMode is BaseButton.DrawModeEnum.Hover or BaseButton.DrawModeEnum.Pressed;

            panel.Panel.Texture = active ? _activePanelTexture : _inactivePanelTexture;
            panel.Button.Label.FontColorOverride = active ? HoverTextColor : drawMode switch
            {
                BaseButton.DrawModeEnum.Pressed => PressTextColor,
                BaseButton.DrawModeEnum.Hover => HoverTextColor,
                _ => Color.White
            };
        }
    }

    private sealed class MenuPanelVisual(Button button, TextureRect panel)
    {
        public Button Button { get; } = button;
        public TextureRect Panel { get; } = panel;
    }
}
