using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client.MainMenu.UI;

[GenerateTypedNameReferences]
public sealed partial class MainMenuControl : Control
{
    public const string StyleIdentifierMainMenu = "mainMenu";
    public const string StyleIdentifierMainMenuVBox = "mainMenuVBox";

    private float _animationTime;
    private Vector2 _backgroundOffset;

    public MainMenuControl(IResourceCache resCache, IConfigurationManager configMan)
    {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(Background, LayoutContainer.LayoutPreset.Wide);

        LayoutContainer.SetAnchorPreset(VBox, LayoutContainer.LayoutPreset.TopRight);
        LayoutContainer.SetMarginRight(VBox, -25);
        LayoutContainer.SetMarginTop(VBox, 30);
        LayoutContainer.SetGrowHorizontal(VBox, LayoutContainer.GrowDirection.Begin);

        var logoTexture = resCache.GetResource<TextureResource>("/Textures/Logo/logo.png");
        Logo.Texture = logoTexture;

        var currentUserName = configMan.GetCVar(CVars.PlayerName);
        UsernameBox.Text = currentUserName;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _animationTime += (float) args.DeltaSeconds;

        var targetOffset = new Vector2(
            MathF.Sin(_animationTime * 0.05f) * 10f,
            MathF.Cos(_animationTime * 0.035f) * 6f);

        var smoothing = 1f - MathF.Exp(-3.5f * (float) args.DeltaSeconds);
        _backgroundOffset = Vector2.Lerp(_backgroundOffset, targetOffset, smoothing);

        Background.Margin = new Thickness(
            -48f + _backgroundOffset.X,
            -32f + _backgroundOffset.Y,
            -48f - _backgroundOffset.X,
            -32f - _backgroundOffset.Y);
    }
}
