using Content.Client._Mythos.UserInterface.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Mythos.UserInterface.Systems.Vitals.Widgets;

// Mythos: Bottom HUD strip carrying HP and Qi orbs flanking the central hotbar.
// Orbs are circular OrbControl instances drawn with primitives (no placeholder
// textures needed); the hotbar is a Mythos-themed 8-slot widget.
[GenerateTypedNameReferences]
public sealed partial class VitalsOrbsBar : UIWidget
{
    public VitalsOrbsBar()
    {
        RobustXamlLoader.Load(this);

        HpOrb.FrameColor = Color.Black;
        HpOrb.BackplateColor = MythosPalette.Ink;
        HpOrb.FillColor = MythosPalette.HpFill;
        HpOrb.RingColor = MythosPalette.AccentStrong;
        HpOrb.SurfaceColor = MythosPalette.MoonWhite;

        QiOrb.FrameColor = Color.Black;
        QiOrb.BackplateColor = MythosPalette.Ink;
        QiOrb.FillColor = MythosPalette.QiFill;
        QiOrb.RingColor = MythosPalette.MoonWhite;
        QiOrb.SurfaceColor = MythosPalette.AccentStrong;
    }

    public void SetHp(float current, float max)
    {
        HpOrb.MaxValue = max <= 0f ? 1f : max;
        HpOrb.Value = current;
        HpOrb.ToolTip = $"HP: {current:F0} / {max:F0}";
    }

    public void SetQi(float current, float max)
    {
        QiOrb.MaxValue = max <= 0f ? 1f : max;
        QiOrb.Value = current;
        QiOrb.ToolTip = $"Qi: {current:F0} / {max:F0}";
    }
}
