using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mythos.UserInterface.Systems.Stats.Widgets;

// Mythos: Name + class + XP composite. Lives inside StatsPanel for the V2 mockup;
// extracted as its own widget so it can move to a dedicated HUD slot later.
[GenerateTypedNameReferences]
public sealed partial class NameClassBadge : UIWidget
{
    public NameClassBadge()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetCharacter(string name, string className, int level, float xp, float xpToNext)
    {
        NameLabel.Text = name;
        ClassLabel.Text = $"Lv. {level}  {className}";
        XpBar.MaxValue = xpToNext <= 0f ? 1f : xpToNext;
        XpBar.Value = xp;
        XpBar.ToolTip = $"XP: {xp:F0} / {xpToNext:F0}";
    }
}
