using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mythos.UserInterface.Systems.Stats.Widgets;

// Mythos: Stats panel for the V2 HUD. Contents are mounted inside MythosCharacterWindow
// (opened via the Character tab). Hosts NameClassBadge and a 6-row stats grid.
[GenerateTypedNameReferences]
public sealed partial class StatsPanel : UIWidget
{
    public StatsPanel()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetCharacter(string name, string className, int level, float xp, float xpToNext)
    {
        Badge.SetCharacter(name, className, level, xp, xpToNext);
    }

    public void SetStats(float hp, float qi, int atk, int def, int spirit, int dex)
    {
        HpValue.Text = $"{hp:F0}";
        QiValue.Text = $"{qi:F0}";
        AtkValue.Text = atk.ToString();
        DefValue.Text = def.ToString();
        SpiritValue.Text = spirit.ToString();
        DexValue.Text = dex.ToString();
    }
}
