using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class DefaultGameScreen : InGameScreen
{
    public DefaultGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(OldHudRoot, LayoutPreset.Wide);
        SetAnchorPreset(MythosHudRoot, LayoutPreset.Wide);
        SetAnchorPreset(EquipmentPanel, LayoutPreset.Wide);
        SetAnchorPreset(ChatPanel, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(TopLeft, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.TopRight, margin: 10);

        MainViewport.OnResized += ResizeActionContainer;
        Inventory.OnResized += ResizeActionContainer;
    }

    private void ResizeActionContainer()
    {
        float indent = Inventory.Size.Y + TopBar.Size.Y + 40;
        Actions.ActionsContainer.MaxGridHeight = MainViewport.Size.Y - indent;
    }

    public override ChatBox ChatBox => Chat;

    public override void SetChatSize(Vector2 size)
    {
    }

    public override void SetOldHudVisible(bool visible)
    {
        OldHudRoot.Visible = visible;
    }

    public override (float Left, float Right) GetMythosViewportOcclusionPixels()
    {
        var left = EquipmentPanel.Visible
            ? EquipmentPanel.CoveredWidth * EquipmentPanel.UIScale
            : 0f;

        var chatLeft = ChatPanel.GlobalPixelPosition.X + ChatPanel.PanelBounds.Left * ChatPanel.UIScale;
        var right = ChatPanel.Visible
            ? MathF.Max(0f, PixelWidth - chatLeft)
            : 0f;

        return (left, right);
    }
}
