using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mythos.UserInterface.Systems.Character.Controls;

// Mythos: 19-slot equipment paper-doll for the V2 HUD. Slots are SlotControl
// instances created programmatically so the count and labels can be tuned without
// rewriting XAML. Slot wiring to inventory components lands post-mockup.
[GenerateTypedNameReferences]
public sealed partial class EquipmentSlotsControl : UIWidget
{
    public const int SlotCount = 12;

    // Demo slot names for the mockup. Labels show on hover. 4 rows x 3 columns.
    private static readonly string[] DemoSlotNames =
    {
        "Head",   "Neck",   "Mask",
        "Outer",  "Inner",  "Belt",
        "Back",   "Gloves", "Shoes",
        "ID",     "Charm",  "Bag",
    };

    public EquipmentSlotsControl()
    {
        RobustXamlLoader.Load(this);
        BuildSlots();
    }

    public IEnumerable<SlotControl> Slots
    {
        get
        {
            foreach (var child in SlotGrid.Children)
            {
                if (child is SlotControl s)
                    yield return s;
            }
        }
    }

    private void BuildSlots()
    {
        for (var i = 0; i < SlotCount; i++)
        {
            var name = DemoSlotNames[i];
            var btn = new SlotButton
            {
                SlotName = name,
                ToolTip = name,
                ButtonTexturePath = "Slots/back",
                MinSize = new System.Numerics.Vector2(48, 48),
            };
            SlotGrid.AddChild(btn);
        }
    }
}
