using Content.Client._Mythos.UserInterface.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;

namespace Content.Client._Mythos.UserInterface.Systems.Character.Controls;

// Mythos: Character portrait for the V2 HUD. Hosts a SpriteView locked to south-facing
// so the rendered character art always reads as a "portrait" pose regardless of the
// in-world facing. CharacterUIController (Mythos namespace) sets the entity to the
// local player on attach/detach.
[GenerateTypedNameReferences]
public sealed partial class PortraitControl : UIWidget
{
    public PortraitControl()
    {
        RobustXamlLoader.Load(this);

        // Tinted backdrop so the empty portrait reads as "portrait area" rather than
        // a stray dark box before the player attaches to a body.
        PortraitFrame.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = MythosPalette.SurfaceMuted.WithAlpha(0.85f),
            BorderColor = MythosPalette.EdgeBright.WithAlpha(0.6f),
            BorderThickness = new Thickness(1),
        };
    }

    public void SetEntity(EntityUid? entity)
    {
        Portrait.SetEntity(entity);
    }
}
