using System.Numerics;
using Content.Client._Mythos.UserInterface.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Mythos.UserInterface.Systems.Hotbar.Widgets;

// Mythos: V2 HUD bottom hotbar - eight numbered placeholder slots styled with the
// Mythos cyan palette. Decoupled from upstream HotbarGui so the screenshot mockup
// shows clean numbered buttons rather than R/L hand slots and inventory items. Real
// keybind / action wiring lands post-mockup.
[GenerateTypedNameReferences]
public sealed partial class MythosHotbar : UIWidget
{
    public const int SlotCount = 8;

    public MythosHotbar()
    {
        RobustXamlLoader.Load(this);
        BuildSlots();
    }

    private void BuildSlots()
    {
        var slotBox = new StyleBoxFlat
        {
            BackgroundColor = MythosPalette.SurfaceMuted.WithAlpha(0.85f),
            BorderColor = MythosPalette.EdgeBright.WithAlpha(0.7f),
            BorderThickness = new Thickness(1),
        };

        for (var i = 1; i <= SlotCount; i++)
        {
            var slot = new PanelContainer
            {
                MinSize = new Vector2(44, 44),
                PanelOverride = slotBox,
                ToolTip = $"Slot {i}",
            };
            slot.AddChild(new Label
            {
                Text = i.ToString(),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                FontColorOverride = MythosPalette.MoonWhite,
            });
            SlotRow.AddChild(slot);
        }
    }
}
