using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mythos.TileSpawn;

[GenerateTypedNameReferences]
public sealed partial class MythosTileSpawnWindow : DefaultWindow
{
    public MythosTileSpawnWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Opened()
    {
        base.Opened();
        SearchBar.GrabKeyboardFocus();
    }
}
