using System.Numerics;
using Content.Client.UserInterface.Screens;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Mythos.UserInterface.Screens;

// Mythos: V2 HUD reskin entry. Loaded when ui.layout=Mythos. Mounts a viewport,
// a populated-but-hidden OldHudRoot (so upstream UIControllers' OnStateEntered widget
// lookups still resolve), and a Mythos HUD root populated by the V2 widgets.
[GenerateTypedNameReferences]
public sealed partial class MythosGameScreen : InGameScreen
{
    public MythosGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(OldHudRoot, LayoutPreset.Wide);
        SetAnchorPreset(MythosHudRoot, LayoutPreset.Wide);

        SetAnchorAndMarginPreset(TopLeft, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.TopRight, margin: 10);

        // Mythos: top menu bar (Character / Inventory / Crafting / Admin / Sandbox / etc.).
        // Anchored top-left of MythosHudRoot so it stays visible even when OldHudRoot
        // is hidden. Upstream UIControllers' GetActiveUIWidgetOrNull<GameTopMenuBar>()
        // resolves to this same instance regardless of which root it's mounted in.
        SetAnchorAndMarginPreset(TopBar, LayoutPreset.TopLeft, margin: 10);

        // Mythos: equipment chrome anchors full-screen Wide and self-positions on
        // the left edge via its own ArrangeOverride.
        SetAnchorPreset(EquipmentPanel, LayoutPreset.Wide);

        // Mythos: chat chrome anchors right-edge but with a top inset so it can't
        // climb above the location pill, and a bottom inset so it can't paint over
        // the vitals strip. Inside this allocated rect, MythosChatPanel.ArrangeOverride
        // still does its own vertical-centering math, just within a smaller area.
        SetAnchorPreset(ChatPanel, LayoutPreset.Wide);
        LayoutContainer.SetMarginTop(ChatPanel, 50);
        LayoutContainer.SetMarginBottom(ChatPanel, -100);

        // Mythos: vitals strip (orbs + 8-slot Mythos hotbar). SetAnchorAndMarginPreset
        // measures the widget and computes MarginTop = -widgetHeight so the strip sits
        // ABOVE the bottom anchor instead of off-screen below it. Using margin: 0 keeps
        // the widget full-width so the inner spacer-pattern centers content on the
        // screen midline.
        SetAnchorAndMarginPreset(Vitals, LayoutPreset.BottomWide, margin: 0);

        // Mythos: location pill anchored to the top-right corner. XAML carries the
        // full default text + a 260x32 MinSize so SetAnchorAndMarginPreset's measure
        // pass produces accurate bounds and the pill doesn't clip when LocationUIController
        // applies the live values later.
        SetAnchorAndMarginPreset(LocationTime, LayoutPreset.TopRight, margin: 10);
    }

    public override ChatBox ChatBox => Chat;

    public override void SetChatSize(Vector2 size)
    {
    }

    public override void SetOldHudVisible(bool visible)
    {
        OldHudRoot.Visible = visible;
    }

    public override (float Left, float Right) GetMythosViewportOcclusionPixels()
    {
        var left = EquipmentPanel.Visible
            ? EquipmentPanel.CoveredWidth * EquipmentPanel.UIScale
            : 0f;

        var chatLeft = ChatPanel.GlobalPixelPosition.X + ChatPanel.PanelBounds.Left * ChatPanel.UIScale;
        var right = ChatPanel.Visible
            ? MathF.Max(0f, PixelWidth - chatLeft)
            : 0f;

        return (left, right);
    }
}
