using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
// Mythos: unsealed so MythosCharacterWindow can subclass and override layout for the V2 HUD.
[Virtual]
public partial class CharacterWindow : DefaultWindow
{
    public CharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
