using System.Linq;
using Content.Client.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mythos.Lobby;

/// <summary>
/// Mythos: per-category feature picker (one tab inside the Features
/// chargen panel).
///
/// Layout follows upstream's per-feature pattern: each feature has its
/// own palette button that expands collapsible color sliders below the
/// item. The Mythos addition is invisible: every slider reads from and
/// writes to the shared <see cref="MarkingsViewModel"/> per-category
/// color memory, so swapping features inside a category preserves the
/// player's chosen palette and live-tints every preview thumbnail.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MythosCategoryPicker : BoxContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private readonly MarkingsViewModel _markingsModel;
    private readonly MythosCategoryBucket _bucket;
    private readonly SpriteSystem _sprite;

    private readonly List<MythosFeatureItem> _items = new();

    public MythosCategoryPicker(MarkingsViewModel model, MythosCategoryBucket bucket)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _markingsModel = model;
        _bucket = bucket;
        _sprite = _entity.System<SpriteSystem>();

        SeedFromSelectedMarking();
        BuildItems();

        SearchBar.OnTextChanged += _ =>
        {
            var q = SearchBar.Text.Trim();
            foreach (var item in _items)
                item.SetVisibleByQuery(q);
        };
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _markingsModel.CategoryColorsChanged += OnCategoryColorsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _markingsModel.CategoryColorsChanged -= OnCategoryColorsChanged;
    }

    private void OnCategoryColorsChanged(string category)
    {
        if (category != _bucket.Category)
            return;

        // The slider that triggered this change has already updated its
        // own marking. Propagate the same colors to every OTHER selected
        // marking in this category (limited to color slots they have, so
        // a 1-slot earring next to a 3-slot tail won't crash) and re-tint
        // every visible thumbnail.
        var colors = _markingsModel.GetCategoryColors(_bucket.Category);
        if (colors is not null)
        {
            foreach (var (id, proto) in _bucket.Markings)
            {
                if (_markingsModel.GetMarking(_bucket.Organ, _bucket.Layer, id) is null)
                    continue;
                var max = System.Math.Min(colors.Count, proto.ColorSlotCount());
                for (var i = 0; i < max; i++)
                    _markingsModel.TrySetMarkingColor(_bucket.Organ, _bucket.Layer, id, i, colors[i]);
            }
        }

        foreach (var item in _items)
            item.OnCategoryColorsChanged();
    }

    private void SeedFromSelectedMarking()
    {
        if (_markingsModel.GetCategoryColors(_bucket.Category) is not null)
            return;
        foreach (var (id, _) in _bucket.Markings)
        {
            var live = _markingsModel.GetMarking(_bucket.Organ, _bucket.Layer, id);
            if (live is { } m && m.MarkingColors.Count > 0)
            {
                _markingsModel.SeedCategoryColors(_bucket.Category, m.MarkingColors.ToList());
                return;
            }
        }
    }

    private void BuildItems()
    {
        Items.RemoveAllChildren();
        _items.Clear();
        foreach (var (id, proto) in _bucket.Markings.OrderBy(kv => Loc.GetString($"marking-{kv.Key}")))
        {
            var item = new MythosFeatureItem(_markingsModel, _bucket, proto, _sprite);
            Items.AddChild(item);
            _items.Add(item);
        }
    }
}
