using System;
using Content.Client.Humanoid;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Mythos.Lobby;

/// <summary>
/// Mythos: one feature thumbnail inside a <see cref="MythosCategoryPicker"/>.
///
/// Mirrors upstream <c>LayerMarkingItem</c>'s layout: thumbnail, select
/// toggle, and a palette button that expands collapsible color sliders
/// below the row. The Mythos addition: every slider reads from and
/// writes to the per-category color memory, so all visible feature items
/// in a category stay in sync — adjusting Hair_Long's primary slider
/// updates Hair_Short's stored primary color too, and selecting
/// Hair_Short later inherits that palette without resetting.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MythosFeatureItem : BoxContainer
{
    private readonly MarkingsViewModel _model;
    private readonly MythosCategoryBucket _bucket;
    private readonly MarkingPrototype _proto;
    private readonly SpriteSystem _sprite;

    private readonly List<(TextureRect Rect, int ColorSlot)> _layerRects = new();

    private List<ColorSelectorSliders>? _colorSliders;
    private readonly Dictionary<string, Button> _toggleButtons = new();

    public MythosFeatureItem(MarkingsViewModel model, MythosCategoryBucket bucket, MarkingPrototype proto, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        _model = model;
        _bucket = bucket;
        _proto = proto;
        _sprite = sprite;

        SelectButton.Text = Loc.GetString($"marking-{_proto.ID}");
        BuildThumbnail();
        BuildToggles();
        ApplyTint(_model.GetCategoryColors(_bucket.Category));
        RefreshSelectionState();

        SelectButton.OnPressed += _ =>
        {
            if (_model.IsMarkingSelected(_bucket.Organ, _bucket.Layer, _proto.ID))
            {
                _model.TryDeselectMarking(_bucket.Organ, _bucket.Layer, _proto.ID);
            }
            else if (_model.TrySelectMarking(_bucket.Organ, _bucket.Layer, _proto.ID))
            {
                // Apply every piece of synced category state to the
                // freshly-selected marking so the user inherits the
                // palette, size slider, variant dropdown, and toggles
                // without re-setting them.
                _model.ApplyCategoryStateToMarking(_bucket.Category, _bucket.Organ, _bucket.Layer, _proto.ID);
            }
        };

        ColorsButton.OnPressed += _ =>
        {
            ColorsContainer.Visible = ColorsButton.Pressed;
            if (ColorsButton.Pressed && _colorSliders is null)
                BuildColorSliders();
        };
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        // Without these the UI desyncs from the model when upstream's
        // limit enforcement deselects sibling markings as a side effect
        // of selecting this one (e.g. tails are limit=1 — picking Fox2
        // pushes out Fox without telling the old item, which then shows
        // a stuck Pressed state and a missing palette button).
        _model.MarkingsReset += RefreshSelectionState;
        _model.MarkingsChanged += OnMarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _model.MarkingsReset -= RefreshSelectionState;
        _model.MarkingsChanged -= OnMarkingsChanged;
    }

    private void OnMarkingsChanged(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        if (organ != _bucket.Organ || layer != _bucket.Layer)
            return;
        RefreshSelectionState();
    }

    public void RefreshSelectionState()
    {
        var selected = _model.IsMarkingSelected(_bucket.Organ, _bucket.Layer, _proto.ID);
        SelectButton.Pressed = selected;
        ColorsButton.Visible = selected
            && _model.IsMarkingColorCustomizable(_bucket.Organ, _bucket.Layer, _proto.ID);
        if (!selected && ColorsButton.Pressed)
        {
            ColorsButton.Pressed = false;
            ColorsContainer.Visible = false;
        }
        // Mythos: toggle row only shown when this item is currently
        // selected AND the prototype declares any toggles.
        TogglesContainer.Visible = selected && _proto.MythosToggles is { Count: > 0 };
        SyncToggleButtons();
    }

    /// <summary>
    /// Called by <see cref="MythosCategoryPicker"/> when the category's
    /// color memory changes. Syncs the slider values (if expanded) and
    /// re-tints the thumbnail.
    /// </summary>
    public void OnCategoryColorsChanged()
    {
        var colors = _model.GetCategoryColors(_bucket.Category);
        ApplyTint(colors);
        if (_colorSliders is null || colors is null)
            return;
        for (var i = 0; i < _colorSliders.Count && i < colors.Count; i++)
            _colorSliders[i].Color = colors[i];
    }

    /// <summary>
    /// Called by <see cref="MythosCategoryPicker"/> when the category's
    /// toggle memory changes. Updates the toggle buttons' Pressed state
    /// to match the synced value.
    /// </summary>
    public void OnCategoryTogglesChanged() => SyncToggleButtons();

    /// <summary>
    /// Called by <see cref="MythosCategoryPicker"/> when the category's
    /// variant memory changes. Re-sources the thumbnail textures for the
    /// new variant so each size item previews the active silhouette /
    /// arrangement instead of the canonical default.
    /// </summary>
    public void OnCategoryVariantChanged()
    {
        BuildThumbnail();
        ApplyTint(_model.GetCategoryColors(_bucket.Category));
    }

    /// <summary>
    /// Mythos: true if this prototype carries an explicit sprite list
    /// for the named variant. Used by the category picker to hide
    /// per-variant-incompatible size items so the user only sees
    /// reachable combinations (e.g., picking Tentacle hides sizes that
    /// don't have tentacle artwork).
    /// </summary>
    public bool SupportsVariant(string? variant)
    {
        if (variant is null)
            return true;
        if (_proto.MythosVariants is null || _proto.MythosVariants.Count == 0)
            return true;
        return _proto.MythosVariantStates is { } states && states.ContainsKey(variant);
    }

    private void BuildToggles()
    {
        TogglesContainer.RemoveAllChildren();
        _toggleButtons.Clear();
        if (_proto.MythosToggles is not { } names)
            return;
        foreach (var name in names)
        {
            var btn = new Button
            {
                Text = GetToggleLabel(name),
                ToggleMode = true,
            };
            var localName = name;
            btn.OnPressed += _ =>
            {
                _model.SetCategoryToggle(_bucket.Category, localName, btn.Pressed);
                // Push directly onto this marking's instance too so the
                // currently-applied marking flips its sprite list before
                // the category fan-out catches up.
                _model.TrySetMarkingMythosToggle(_bucket.Organ, _bucket.Layer, _proto.ID, localName, btn.Pressed);
            };
            TogglesContainer.AddChild(btn);
            _toggleButtons[name] = btn;
        }
    }

    private void SyncToggleButtons()
    {
        if (_toggleButtons.Count == 0)
            return;
        var toggles = _model.GetCategoryToggles(_bucket.Category);
        foreach (var (name, btn) in _toggleButtons)
        {
            var v = toggles is not null && toggles.TryGetValue(name, out var b) && b;
            btn.Pressed = v;
        }
    }

    private string GetToggleLabel(string name)
    {
        var key = $"mythos-feature-toggle-{name}";
        if (Loc.TryGetString(key, out var localized))
            return localized;
        // Sandbox-safe fallback: just substitute spaces for the OV
        // toggle naming convention's underscores. Title-casing got us
        // a sandbox violation because every char-vs-string op the
        // C# compiler would pick (range slice, char + string concat,
        // ToUpper) routes through a ReadOnlySpan<char> ctor that
        // Mythos's sandbox forbids. The locale entries in
        // chargen/features/ui.ftl already provide the polished labels
        // (Open / Functional / Lactating / etc.); this fallback only
        // shows up if a new toggle name lands without a locale entry.
        return name.Replace('_', ' ');
    }

    private void BuildColorSliders()
    {
        ColorsContainer.RemoveAllChildren();
        _colorSliders = new List<ColorSelectorSliders>();

        var slotCount = _proto.ColorSlotCount();
        var colors = _model.GetCategoryColors(_bucket.Category);

        for (var slot = 0; slot < slotCount; slot++)
        {
            var row = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };
            row.AddChild(new Label { Text = GetSlotLabel(slot) });
            var selector = new ColorSelectorSliders { SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv };
            row.AddChild(selector);
            ColorsContainer.AddChild(row);

            // Initial value: category memory if seeded, else the
            // marking's current color.
            if (colors is not null && slot < colors.Count)
                selector.Color = colors[slot];
            else if (_model.GetMarking(_bucket.Organ, _bucket.Layer, _proto.ID) is { } m
                     && slot < m.MarkingColors.Count)
                selector.Color = m.MarkingColors[slot];

            _colorSliders.Add(selector);

            var idx = slot;
            selector.OnColorChanged += _ =>
            {
                // Update this marking's color directly (no fan-out — the
                // category-level event below propagates to other selected
                // markings, with bound checks).
                _model.TrySetMarkingColor(_bucket.Organ, _bucket.Layer, _proto.ID, idx, selector.Color);
                // Update category memory; fires CategoryColorsChanged
                // which re-tints all thumbnails and syncs sibling sliders.
                _model.SetCategoryColor(_bucket.Category, idx, selector.Color);
            };
        }
    }

    /// <summary>
    /// Per-slot color label. First tries a category-specific override
    /// (mythos-feature-color-slot-{Category}-{slot}) so OV-style labels
    /// like "Member" / "Sack" / "Nethers" / "Outer" land in the right
    /// category. Falls back to the generic Primary / Secondary / Tertiary
    /// keys, then to a hard-coded "Color N" string.
    /// </summary>
    private string GetSlotLabel(int slot)
    {
        var categoryKey = $"mythos-feature-color-slot-{_bucket.Category}-{slot}";
        if (Loc.TryGetString(categoryKey, out var categoryLabel))
            return categoryLabel;
        var genericKey = $"mythos-feature-color-slot-{slot}";
        if (Loc.TryGetString(genericKey, out var generic))
            return generic;
        return $"Color {slot + 1}";
    }

    private void BuildThumbnail()
    {
        ThumbnailRoot.RemoveAllChildren();
        _layerRects.Clear();

        // Mythos: preview the variant the player has currently selected
        // so each size item shows the right silhouette (e.g., flipping
        // the dropdown from Plain to Knotted retints AND repaints the
        // thumbnails). Falls back to default Sprites when the proto has
        // no variant axis or the active variant has no entry.
        var variant = _model.GetCategoryVariant(_bucket.Category);
        var sprites = _proto.GetActiveSprites(null, null, variant);

        var stack = new LayoutContainer { HorizontalExpand = true, VerticalExpand = true };
        ThumbnailRoot.AddChild(stack);
        for (var i = 0; i < sprites.Count; i++)
        {
            if (sprites[i] is not SpriteSpecifier.Rsi)
                continue;
            var rect = new TextureRect
            {
                Texture = _sprite.Frame0(sprites[i]),
                TextureScale = new System.Numerics.Vector2(2, 2),
            };
            stack.AddChild(rect);
            LayoutContainer.SetAnchorAndMarginPreset(rect, LayoutContainer.LayoutPreset.Center);
            _layerRects.Add((rect, _proto.GetSpriteColorIndex(i)));
        }
    }

    public void ApplyTint(IReadOnlyList<Color>? colors)
    {
        foreach (var (rect, slot) in _layerRects)
        {
            if (colors is null || slot >= colors.Count)
                rect.Modulate = Color.White;
            else
                rect.Modulate = colors[slot];
        }
    }

    public void SetVisibleByQuery(string query)
    {
        if (string.IsNullOrEmpty(query))
        {
            Visible = true;
            return;
        }
        var name = Loc.GetString($"marking-{_proto.ID}");
        Visible = name.Contains(query, StringComparison.OrdinalIgnoreCase);
    }
}
