// Mythos: chargen "Clothing" tab.
//
// Iterates every entity prototype that has the MythosClothing component
// (inherited from OVRoguetownClothingBase, the manual root authored at
// Resources/Prototypes/_Mythos/Clothing/_root.yml), groups them by their
// primary inventory slot, and surfaces one tab per non-empty slot. Each
// tab is a grid of MythosClothingItem thumbnails sized to the available
// width, mirroring the MythosFeaturePicker layout used by the Features
// tab.
//
// Selection is per-slot (one item picked per sub-tab; clicking the
// active item deselects it -- same UX as the Features picker). State
// persists across tab switches and is held in
// <see cref="_selectionBySlot"/>; a future pass can read this dict
// to thread choices into HumanoidCharacterProfile / loadout spawn.
using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared.Clothing.Components;
using Content.Shared.Clothing._Mythos;
using Content.Shared.Inventory;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Log;
using Robust.Shared.Prototypes;

namespace Content.Client._Mythos.Lobby;

[GenerateTypedNameReferences]
public sealed partial class MythosClothingPicker : Control
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IComponentFactory _componentFactory = default!;

    /// <summary>
    /// Slot tab ordering, head-to-feet. Items are bucketed into the FIRST
    /// slot in this list whose flag the item declares, so a multi-slot
    /// helmet with HEAD|BELT lands under Head rather than Belt.
    /// </summary>
    private static readonly (SlotFlags Flag, string Title)[] SlotOrder =
    {
        (SlotFlags.HEAD,          "Head"),
        (SlotFlags.MASK,          "Mask"),
        (SlotFlags.NECK,          "Neck"),
        (SlotFlags.CLOAK,         "Cloak"),
        (SlotFlags.OUTERCLOTHING, "Outer"),
        (SlotFlags.INNERCLOTHING, "Inner"),
        (SlotFlags.BELT,          "Belt"),
        (SlotFlags.BACK,          "Back"),
        (SlotFlags.GLOVES,        "Hands"),
        (SlotFlags.LEGS,          "Pants"),
        (SlotFlags.FEET,          "Shoes"),
        (SlotFlags.EYES,          "Eyes"),
        (SlotFlags.EARS,          "Ears"),
    };

    /// <summary>
    /// Component name that flags a prototype as Mythos-managed clothing.
    /// Comes from <c>MythosClothingComponent</c> declared on the manual
    /// <c>OVRoguetownClothingBase</c> root in
    /// <c>Resources/Prototypes/_Mythos/Clothing/_root.yml</c>; SS14
    /// merges it into every concrete descendant's component dictionary
    /// at prototype-load time, so checking the post-merge components
    /// gives us a robust "is this an OV item?" filter.
    /// </summary>
    /// <remarks>
    /// The natural alternative -- walking the parent chain via
    /// <see cref="IPrototypeManager.EnumerateParents{T}"/> looking for
    /// <c>OVRoguetownClothingBase</c> -- does NOT work in SS14: abstract
    /// prototypes are consumed at load time and the prototype manager's
    /// <c>HasIndex</c> / <c>TryIndex</c> / <c>EnumerateParents</c> APIs
    /// silently skip them post-merge. The diagnostic test
    /// <c>ProbeOvInheritanceChain</c> in
    /// <c>Content.IntegrationTests/Tests/_Mythos/ClothingPortDiagnosticTest.cs</c>
    /// pins this behavior down.
    /// </remarks>
    private const string MythosClothingMarker = "MythosClothing";

    /// <summary>
    /// Minimum cell width in pixels. Sized to comfortably fit the 64x64
    /// thumbnail panel, the 4px separator, and a button wide enough for
    /// most item names without clipping. Names longer than this clip
    /// (ClipText=true on the button); their full text remains visible
    /// in the tooltip. The number is intentionally a bit conservative;
    /// dial up if more than a handful of items end up clipped.
    /// </summary>
    private const int MinCellWidthPx = 250;

    /// <summary>
    /// Currently selected item per slot. Populated in
    /// <see cref="OnItemToggled"/> and consulted when re-rendering or
    /// (eventually) committing the choice to the player's profile.
    /// One slot may have at most one selected item; clicking the
    /// active item again deselects it, leaving the slot empty.
    /// </summary>
    private readonly Dictionary<SlotFlags, MythosClothingItem> _selectionBySlot = new();

    /// <summary>
    /// Fired whenever the per-slot selection state changes (item picked,
    /// deselected, or replaced). The lobby preview subscribes to this
    /// to refresh which clothing entities are equipped on the chargen
    /// dummy, mirroring how the Markings model fires
    /// <c>MarkingsChanged</c> to drive the lightweight preview reload
    /// for features.
    /// </summary>
    public event Action? SelectionChanged;

    /// <summary>
    /// Snapshot of currently selected entity prototypes keyed by primary
    /// slot. Slots without a selection are absent from the dict (use
    /// <see cref="ManagedSlots"/> to know which slots the picker owns
    /// and should be cleared if missing here). Returned as a fresh dict
    /// so callers can hold a reference without seeing live mutations.
    /// </summary>
    public IReadOnlyDictionary<SlotFlags, EntityPrototype> Selections
    {
        get
        {
            var snapshot = new Dictionary<SlotFlags, EntityPrototype>(_selectionBySlot.Count);
            foreach (var (flag, item) in _selectionBySlot)
                snapshot[flag] = item.Prototype;
            return snapshot;
        }
    }

    /// <summary>
    /// The set of slot flags this picker manages (every entry in
    /// <see cref="SlotOrder"/>). Consumers use this to scope inventory
    /// clears to slots the player can pick clothing for, leaving
    /// non-managed slots (POCKETs, IDCARD, etc.) untouched.
    /// </summary>
    public static IReadOnlyCollection<SlotFlags> ManagedSlots { get; } =
        SlotOrder.Select(s => s.Flag).ToArray();

    /// <summary>
    /// Snapshot of currently selected entity-prototype IDs keyed by
    /// inventory-template slot NAME (e.g. "outerClothing", "head"). This
    /// is the shape <see cref="HumanoidCharacterProfile.MythosClothingSelections"/>
    /// stores: name-keyed so it round-trips through the network /
    /// database without depending on the SlotFlags numeric values.
    /// Returned as a fresh dict so callers can hold a reference without
    /// seeing live mutations.
    /// </summary>
    public Dictionary<string, EntProtoId> SelectionsByName
    {
        get
        {
            var snapshot = new Dictionary<string, EntProtoId>(_selectionBySlot.Count);
            foreach (var (flag, item) in _selectionBySlot)
            {
                var name = MythosClothingSlots.FlagToName(flag);
                if (name == null)
                    continue;
                snapshot[name] = item.Prototype.ID;
            }
            return snapshot;
        }
    }

    /// <summary>
    /// Replay <paramref name="selections"/> (slot-name -> entity-proto ID,
    /// the shape stored on the profile) onto the picker's per-slot
    /// state, suppressing per-toggle <see cref="SelectionChanged"/>
    /// notifications. Fires <see cref="SelectionChanged"/> exactly once
    /// at the end if the post-load state differs from the pre-load
    /// state, so editor save-dirty bookkeeping stays accurate.
    /// </summary>
    /// <remarks>
    /// Selections referencing prototype IDs that no longer exist
    /// (renamed / removed during a port, or coming from a save that
    /// predates a removal) are silently skipped and logged at WARN to
    /// the <c>mythos.clothing.picker</c> sawmill, matching the "soft
    /// skip with logging" policy used by the server spawn path.
    /// </remarks>
    public void LoadFromProfile(IReadOnlyDictionary<string, EntProtoId> selections)
    {
        var sawmill = Logger.GetSawmill("mythos.clothing.picker");

        // Build a target SlotFlags -> proto-ID map first so we can
        // diff against the current selection without reentrant events.
        var target = new Dictionary<SlotFlags, string>();
        foreach (var (slotName, protoId) in selections)
        {
            var flag = MythosClothingSlots.NameToFlag(slotName);
            if (flag == SlotFlags.NONE)
            {
                sawmill.Warning(
                    $"LoadFromProfile: profile referenced unknown slot '{slotName}'; skipping.");
                continue;
            }
            target[flag] = protoId;
        }

        // Walk every grid we built and reconcile selection state.
        _suppressSelectionEvents = true;
        var changed = false;
        try
        {
            // First pass: deselect any item whose slot no longer has a
            // matching target (or whose target points at a different
            // prototype than the currently selected one).
            foreach (var (flag, item) in _selectionBySlot.ToArray())
            {
                if (!target.TryGetValue(flag, out var wantedId)
                    || !string.Equals(wantedId, item.Prototype.ID,
                        StringComparison.Ordinal))
                {
                    item.IsSelected = false;
                    _selectionBySlot.Remove(flag);
                    changed = true;
                }
            }

            // Second pass: select items the profile asks for that
            // aren't already selected. We have to find the
            // MythosClothingItem control instance whose prototype ID
            // matches; iterate the grids we built in BuildTabs.
            foreach (var (flag, wantedId) in target)
            {
                if (_selectionBySlot.TryGetValue(flag, out var current)
                    && string.Equals(current.Prototype.ID, wantedId,
                        StringComparison.Ordinal))
                {
                    continue;
                }
                var match = FindItem(flag, wantedId);
                if (match == null)
                {
                    sawmill.Warning(
                        $"LoadFromProfile: profile referenced unknown / "
                        + $"non-Mythos prototype '{wantedId}' for slot "
                        + $"'{MythosClothingSlots.FlagToName(flag)}'; "
                        + $"skipping.");
                    continue;
                }
                match.IsSelected = true;
                _selectionBySlot[flag] = match;
                changed = true;
            }
        }
        finally
        {
            _suppressSelectionEvents = false;
        }

        if (changed)
            SelectionChanged?.Invoke();
    }

    /// <summary>
    /// Find the <see cref="MythosClothingItem"/> instance bucketed under
    /// <paramref name="flag"/> whose prototype ID matches
    /// <paramref name="protoId"/>, or null if it isn't on the picker
    /// (renamed / removed item, or wrong slot).
    /// </summary>
    private MythosClothingItem? FindItem(SlotFlags flag, string protoId)
    {
        if (!_itemsByFlag.TryGetValue(flag, out var items))
            return null;
        foreach (var item in items)
        {
            if (string.Equals(item.Prototype.ID, protoId, StringComparison.Ordinal))
                return item;
        }
        return null;
    }

    /// <summary>
    /// All grid containers we built, paired with the item list each one
    /// renders. Stored so <see cref="OnPickerResized"/> can recompute
    /// the column count for each tab when the editor window resizes.
    /// </summary>
    private readonly List<GridContainer> _grids = new();

    /// <summary>
    /// All <see cref="MythosClothingItem"/> control instances bucketed by
    /// their primary slot, populated in <see cref="BuildTabs"/>.
    /// Used by <see cref="LoadFromProfile"/> to look up the control that
    /// matches a profile-stored prototype ID without re-walking the UI
    /// tree.
    /// </summary>
    private readonly Dictionary<SlotFlags, List<MythosClothingItem>> _itemsByFlag = new();

    /// <summary>
    /// When true, <see cref="OnItemToggled"/> updates internal state but
    /// suppresses the per-toggle <see cref="SelectionChanged"/> event.
    /// <see cref="LoadFromProfile"/> uses this so a profile load fires
    /// at most one aggregate change event regardless of how many slots
    /// change in the replay.
    /// </summary>
    private bool _suppressSelectionEvents;

    public MythosClothingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        BuildTabs();
        OnResized += OnPickerResized;
    }

    private void BuildTabs()
    {
        var sawmill = Logger.GetSawmill("mythos.clothing.picker");

        // Bucket Mythos-clothing prototypes by primary slot.
        var bySlot = new Dictionary<SlotFlags, List<EntityPrototype>>();
        var totalCount = 0;
        var afterMarker = 0;
        var afterClothingComp = 0;
        var afterSlotPick = 0;
        foreach (var proto in _prototypes.EnumeratePrototypes<EntityPrototype>())
        {
            totalCount++;
            if (!proto.Components.ContainsKey(MythosClothingMarker))
                continue;
            afterMarker++;
            if (!proto.TryGetComponent<ClothingComponent>(out var clothing,
                    _componentFactory))
                continue;
            afterClothingComp++;
            var primary = PickPrimarySlot(clothing.Slots);
            if (primary == SlotFlags.NONE)
                continue;
            afterSlotPick++;
            if (!bySlot.TryGetValue(primary, out var list))
                bySlot[primary] = list = new List<EntityPrototype>();
            list.Add(proto);
        }

        sawmill.Info(
            $"BuildTabs: total={totalCount} mythos-marker={afterMarker} "
            + $"with-clothing-comp={afterClothingComp} "
            + $"with-primary-slot={afterSlotPick} buckets={bySlot.Count}");

        // Build one tab per non-empty slot in display order. Each grid
        // starts with one column; OnPickerResized rebalances once the
        // tab is laid out and we know the actual width.
        var tabIdx = 0;
        foreach (var (flag, title) in SlotOrder)
        {
            if (!bySlot.TryGetValue(flag, out var items))
                continue;

            var scroll = new ScrollContainer
            {
                VerticalExpand = true,
                HorizontalExpand = true,
            };
            var grid = new GridContainer
            {
                Columns = 1,
                HorizontalExpand = true,
            };
            var bucket = new List<MythosClothingItem>(items.Count);
            foreach (var proto in items.OrderBy(p => p.Name))
            {
                var item = new MythosClothingItem(proto);
                item.Toggled += (clicked, on) => OnItemToggled(flag, clicked, on);
                grid.AddChild(item);
                bucket.Add(item);
            }
            _itemsByFlag[flag] = bucket;
            scroll.AddChild(grid);
            SlotTabs.AddChild(scroll);
            SlotTabs.SetTabTitle(tabIdx, title);
            _grids.Add(grid);
            tabIdx++;
        }

        // Empty-state fallback: if NO bucket populated any tab, surface
        // a diagnostic placeholder so the failure mode is visible
        // in-game rather than a layout-bug-looking empty box.
        if (tabIdx == 0)
        {
            var msg = new Label
            {
                Text = $"No Mythos clothing prototypes found.\n"
                       + $"Checked {totalCount} prototypes total; "
                       + $"{afterMarker} had a MythosClothing component, "
                       + $"{afterClothingComp} also had a Clothing component, "
                       + $"{afterSlotPick} had a recognised slot.\n"
                       + $"See the 'mythos.clothing.picker' sawmill in the client log for details.",
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };
            SlotTabs.AddChild(msg);
            SlotTabs.SetTabTitle(0, "(diagnostic)");
            sawmill.Warning("BuildTabs produced 0 tabs; diagnostic placeholder shown.");
        }
    }

    /// <summary>
    /// Enforces the "at most one item selected per slot" invariant.
    /// When an item is toggled on, deselect the previous selection in
    /// the same slot. When toggled off, just forget it.
    /// </summary>
    private void OnItemToggled(SlotFlags slot, MythosClothingItem clicked,
                               bool nowOn)
    {
        var changed = false;
        if (!nowOn)
        {
            // Clicked the active item -> it has just deselected itself.
            // Clear our record if the deselected item matches.
            if (_selectionBySlot.TryGetValue(slot, out var active)
                && active == clicked)
            {
                _selectionBySlot.Remove(slot);
                changed = true;
            }
        }
        else
        {
            // A new item was selected. Silently toggle off the previous
            // selection in this slot (if any) and record the new one.
            if (_selectionBySlot.TryGetValue(slot, out var prior)
                && prior != clicked)
            {
                prior.IsSelected = false;
            }
            _selectionBySlot[slot] = clicked;
            changed = true;
        }

        if (changed && !_suppressSelectionEvents)
            SelectionChanged?.Invoke();
    }

    private void OnPickerResized()
    {
        // Recompute the column count so cells stay at least
        // MinCellWidthPx wide. Hooking OnResized at the picker level
        // catches both initial layout (fired once after first measure)
        // and runtime window resizes.
        if (_grids.Count == 0)
            return;
        var available = (int)Math.Max(0, Width);
        var cols = Math.Max(1, available / MinCellWidthPx);
        foreach (var grid in _grids)
        {
            if (grid.Columns != cols)
                grid.Columns = cols;
        }
    }

    private static SlotFlags PickPrimarySlot(SlotFlags slots)
    {
        foreach (var (flag, _) in SlotOrder)
        {
            if ((slots & flag) != 0)
                return flag;
        }
        return SlotFlags.NONE;
    }
}
