// Mythos: thumbnail + name button for one OV clothing entity prototype,
// rendered as a single cell in MythosClothingPicker's per-slot grid.
// Visual layout mirrors MythosFeatureItem so the Clothing and Features
// chargen tabs feel uniform.
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Mythos.Lobby;

[GenerateTypedNameReferences]
public sealed partial class MythosClothingItem : BoxContainer
{
    /// <summary>
    /// The OV clothing entity prototype this cell represents.
    /// Exposed so the parent picker can identify the selection
    /// without re-reading the button's caption.
    /// </summary>
    public EntityPrototype Prototype { get; }

    /// <summary>
    /// Raised when the user toggles this item on or off. The bool is
    /// the new toggle state. The parent picker wires this to enforce
    /// "at most one selection per sub-tab": when this fires with
    /// <c>true</c>, the picker silently un-toggles any previously
    /// selected sibling item.
    /// </summary>
    public event Action<MythosClothingItem, bool>? Toggled;

    /// <summary>
    /// Get / set the selection state without re-firing the
    /// <see cref="Toggled"/> event. Used by the parent picker to
    /// silently deselect the previously selected sibling when a new
    /// item is picked.
    /// </summary>
    public bool IsSelected
    {
        get => SelectButton.Pressed;
        set
        {
            if (SelectButton.Pressed == value)
                return;
            // Setting Pressed directly does not fire OnPressed/OnToggled
            // (those only trigger from user input), so this is safe to
            // use for the silent-deselect path.
            SelectButton.Pressed = value;
        }
    }

    public MythosClothingItem(EntityPrototype proto)
    {
        RobustXamlLoader.Load(this);
        Prototype = proto;

        ProtoView.SetPrototype(proto.ID);
        SelectButton.Text = proto.Name;
        // Tooltip surfaces the full description AND the full name --
        // useful when the button clips a long name (ClipText=true on
        // the XAML) so the player can still read the original.
        SelectButton.ToolTip = string.IsNullOrEmpty(proto.Description)
            ? proto.Name
            : $"{proto.Name}\n\n{proto.Description}";

        SelectButton.OnToggled += args => Toggled?.Invoke(this, args.Pressed);
    }
}
