using System;
using Content.Client.Humanoid;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Mythos.Lobby;

/// <summary>
/// Mythos: one feature thumbnail inside a <see cref="MythosCategoryPicker"/>.
///
/// Mirrors upstream <c>LayerMarkingItem</c>'s layout: thumbnail, select
/// toggle, and a palette button that expands collapsible color sliders
/// below the row. The Mythos addition: every slider reads from and
/// writes to the per-category color memory, so all visible feature items
/// in a category stay in sync — adjusting Hair_Long's primary slider
/// updates Hair_Short's stored primary color too, and selecting
/// Hair_Short later inherits that palette without resetting.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MythosFeatureItem : BoxContainer
{
    private readonly MarkingsViewModel _model;
    private readonly MythosCategoryBucket _bucket;
    private readonly MarkingPrototype _proto;
    private readonly SpriteSystem _sprite;

    private readonly List<(TextureRect Rect, int ColorSlot)> _layerRects = new();

    private List<ColorSelectorSliders>? _colorSliders;

    public MythosFeatureItem(MarkingsViewModel model, MythosCategoryBucket bucket, MarkingPrototype proto, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        _model = model;
        _bucket = bucket;
        _proto = proto;
        _sprite = sprite;

        SelectButton.Text = Loc.GetString($"marking-{_proto.ID}");
        BuildThumbnail();
        ApplyTint(_model.GetCategoryColors(_bucket.Category));
        RefreshSelectionState();

        SelectButton.OnPressed += _ =>
        {
            if (_model.IsMarkingSelected(_bucket.Organ, _bucket.Layer, _proto.ID))
            {
                _model.TryDeselectMarking(_bucket.Organ, _bucket.Layer, _proto.ID);
            }
            else if (_model.TrySelectMarking(_bucket.Organ, _bucket.Layer, _proto.ID))
            {
                // Apply the category's stored colors to the freshly-
                // selected marking so the user doesn't have to re-tint.
                _model.ApplyCategoryColorsToMarking(_bucket.Category, _bucket.Organ, _bucket.Layer, _proto.ID);
            }
        };

        ColorsButton.OnPressed += _ =>
        {
            ColorsContainer.Visible = ColorsButton.Pressed;
            if (ColorsButton.Pressed && _colorSliders is null)
                BuildColorSliders();
        };
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        // Without these the UI desyncs from the model when upstream's
        // limit enforcement deselects sibling markings as a side effect
        // of selecting this one (e.g. tails are limit=1 — picking Fox2
        // pushes out Fox without telling the old item, which then shows
        // a stuck Pressed state and a missing palette button).
        _model.MarkingsReset += RefreshSelectionState;
        _model.MarkingsChanged += OnMarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _model.MarkingsReset -= RefreshSelectionState;
        _model.MarkingsChanged -= OnMarkingsChanged;
    }

    private void OnMarkingsChanged(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        if (organ != _bucket.Organ || layer != _bucket.Layer)
            return;
        RefreshSelectionState();
    }

    public void RefreshSelectionState()
    {
        var selected = _model.IsMarkingSelected(_bucket.Organ, _bucket.Layer, _proto.ID);
        SelectButton.Pressed = selected;
        ColorsButton.Visible = selected
            && _model.IsMarkingColorCustomizable(_bucket.Organ, _bucket.Layer, _proto.ID);
        if (!selected && ColorsButton.Pressed)
        {
            ColorsButton.Pressed = false;
            ColorsContainer.Visible = false;
        }
    }

    /// <summary>
    /// Called by <see cref="MythosCategoryPicker"/> when the category's
    /// color memory changes. Syncs the slider values (if expanded) and
    /// re-tints the thumbnail.
    /// </summary>
    public void OnCategoryColorsChanged()
    {
        var colors = _model.GetCategoryColors(_bucket.Category);
        ApplyTint(colors);
        if (_colorSliders is null || colors is null)
            return;
        for (var i = 0; i < _colorSliders.Count && i < colors.Count; i++)
            _colorSliders[i].Color = colors[i];
    }

    private void BuildColorSliders()
    {
        ColorsContainer.RemoveAllChildren();
        _colorSliders = new List<ColorSelectorSliders>();

        var slotCount = _proto.ColorSlotCount();
        var colors = _model.GetCategoryColors(_bucket.Category);

        for (var slot = 0; slot < slotCount; slot++)
        {
            var row = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };
            row.AddChild(new Label { Text = GetSlotLabel(slot) });
            var selector = new ColorSelectorSliders { SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv };
            row.AddChild(selector);
            ColorsContainer.AddChild(row);

            // Initial value: category memory if seeded, else the
            // marking's current color.
            if (colors is not null && slot < colors.Count)
                selector.Color = colors[slot];
            else if (_model.GetMarking(_bucket.Organ, _bucket.Layer, _proto.ID) is { } m
                     && slot < m.MarkingColors.Count)
                selector.Color = m.MarkingColors[slot];

            _colorSliders.Add(selector);

            var idx = slot;
            selector.OnColorChanged += _ =>
            {
                // Update this marking's color directly (no fan-out — the
                // category-level event below propagates to other selected
                // markings, with bound checks).
                _model.TrySetMarkingColor(_bucket.Organ, _bucket.Layer, _proto.ID, idx, selector.Color);
                // Update category memory; fires CategoryColorsChanged
                // which re-tints all thumbnails and syncs sibling sliders.
                _model.SetCategoryColor(_bucket.Category, idx, selector.Color);
            };
        }
    }

    /// <summary>
    /// Generic per-slot label. Mythos uses Primary / Secondary / Tertiary
    /// because the same picker hosts categories with very different
    /// semantics (tail outer/inner vs breast areola/nipple) and the
    /// state-name-derived labels read like keys, not English. Per-category
    /// labels are a future polish if needed.
    /// </summary>
    private static string GetSlotLabel(int slot)
    {
        var key = $"mythos-feature-color-slot-{slot}";
        if (Loc.TryGetString(key, out var localized))
            return localized;
        return $"Color {slot + 1}";
    }

    private void BuildThumbnail()
    {
        ThumbnailRoot.RemoveAllChildren();
        _layerRects.Clear();

        var stack = new LayoutContainer { HorizontalExpand = true, VerticalExpand = true };
        ThumbnailRoot.AddChild(stack);
        for (var i = 0; i < _proto.Sprites.Count; i++)
        {
            if (_proto.Sprites[i] is not SpriteSpecifier.Rsi)
                continue;
            var rect = new TextureRect
            {
                Texture = _sprite.Frame0(_proto.Sprites[i]),
                TextureScale = new System.Numerics.Vector2(2, 2),
            };
            stack.AddChild(rect);
            LayoutContainer.SetAnchorAndMarginPreset(rect, LayoutContainer.LayoutPreset.Center);
            _layerRects.Add((rect, _proto.GetSpriteColorIndex(i)));
        }
    }

    public void ApplyTint(IReadOnlyList<Color>? colors)
    {
        foreach (var (rect, slot) in _layerRects)
        {
            if (colors is null || slot >= colors.Count)
                rect.Modulate = Color.White;
            else
                rect.Modulate = colors[slot];
        }
    }

    public void SetVisibleByQuery(string query)
    {
        if (string.IsNullOrEmpty(query))
        {
            Visible = true;
            return;
        }
        var name = Loc.GetString($"marking-{_proto.ID}");
        Visible = name.Contains(query, StringComparison.OrdinalIgnoreCase);
    }
}
