using System.Linq;
using Content.Client.Humanoid;
using Content.Shared.Body;
using Content.Shared.CCVar;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._Mythos.Lobby;

/// <summary>
/// Mythos: chargen "Features" tab picker.
///
/// OV calls everything in <c>icons/mob/sprite_accessory/</c> "features" and
/// presents them as a flat list of categorical sub-tabs (Eyes, Hair, Facial
/// Hair, Accessory, Tail, Snout, Ears, Horns, Frills, ...) ordered the same
/// way every species. SS14's upstream <see cref="MarkingPicker"/> instead
/// nests them under organ categories (Head, Torso, ...) and groups by
/// render layer (HeadTop, HeadSide, ...). Two problems with that for an
/// OV port: render layers conflate distinct categories (Ears, Horns, and
/// Antennas all share HeadTop), and players have to know which organ
/// holds which feature.
///
/// This picker groups by <see cref="MarkingPrototype.Category"/> instead.
/// One tab per OV chargen category in <see cref="OvCategoryOrder" /> so
/// Ears / Horns / Antennas can each get their own tab even though they
/// share a render layer. Each tab hosts a <see cref="MythosCategoryPicker"/>
/// — a category-scoped picker with shared color sliders that persist
/// across feature swaps within the category.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MythosFeaturePicker : Control
{
    [Dependency] private readonly MarkingManager _marking = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    /// <summary>
    /// Categories hidden when <see cref="CCVars.MythosChargenErpFeatures"/>
    /// is false. Matches OV's adult-only customizer set: Penis, Vagina,
    /// Testicles, Breasts, Belly, Butt. Existing markings on these
    /// layers stay applied if the player has them; new selection is
    /// just impossible.
    /// </summary>
    private static readonly HashSet<string> ErpCategories = new()
    {
        "Penis",
        "Vagina",
        "Testicles",
        "Breasts",
        "Belly",
        "Butt",
    };

    private MarkingsViewModel? _markingsModel;

    /// <summary>
    /// OV chargen tab order. Categories not in this list fall to the end
    /// in declaration order. Add new categories here as they're ported
    /// (e.g., Antennas, BackFeature, NeckFeature in their proper slot).
    /// </summary>
    private static readonly string[] OvCategoryOrder =
    {
        "Eyes",
        "Hair",
        "FacialHair",
        "Accessory",
        "FaceDetail",
        "Underwear",
        "Legwear",
        "Piercing",
        "Tail",
        "TailFeature",
        "Snout",
        "Ears",
        "Horns",
        "Frills",
        "Wings",
        "Fluff",
        "Testicles",
        "Penis",
        "Breasts",
        "Vagina",
        "Belly",
        "Butt",
    };

    public MythosFeaturePicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UpdateFeatures();
    }

    public void SetModel(MarkingsViewModel model)
    {
        if (_markingsModel != null)
        {
            _markingsModel.OrganDataChanged -= UpdateFeatures;
            _markingsModel.EnforcementsChanged -= UpdateFeatures;
            _markingsModel.OrganProfileDataChanged -= OnProfileDataChanged;
        }

        _markingsModel = model;

        _markingsModel.OrganDataChanged += UpdateFeatures;
        _markingsModel.EnforcementsChanged += UpdateFeatures;
        _markingsModel.OrganProfileDataChanged += OnProfileDataChanged;

        UpdateFeatures();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        if (_markingsModel is null)
            return;

        _markingsModel.OrganDataChanged += UpdateFeatures;
        _markingsModel.EnforcementsChanged += UpdateFeatures;
        _markingsModel.OrganProfileDataChanged += OnProfileDataChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        if (_markingsModel is null)
            return;

        _markingsModel.OrganDataChanged -= UpdateFeatures;
        _markingsModel.EnforcementsChanged -= UpdateFeatures;
        _markingsModel.OrganProfileDataChanged -= OnProfileDataChanged;
    }

    private void OnProfileDataChanged(bool refresh)
    {
        if (refresh)
            UpdateFeatures();
    }

    /// <summary>
    /// The Mythos eye color picker injected into the Features Eyes tab,
    /// or null if the picker hasn't been built yet (no Mythos species
    /// selected). Editor callers wire this up the same way they wire
    /// the upstream Appearance-tab picker.
    /// </summary>
    public MythosEyesPicker? EyesPicker { get; private set; }

    /// <summary>
    /// Predicate the editor sets to indicate whether the current species
    /// uses the Mythos chargen flow (in which case the Eyes tab is
    /// injected into Features and the Appearance-tab eye picker is
    /// hidden). Defaults to false so vanilla species are unaffected.
    /// </summary>
    public Func<bool>? IsMythosSpecies { get; set; }

    /// <summary>
    /// Raised after a refresh has rebuilt the tabs. Editor uses this to
    /// bind <see cref="EyesPicker"/> to the live profile.
    /// </summary>
    public event Action? FeaturesRebuilt;

    private void UpdateFeatures()
    {
        FeatureTabs.RemoveAllChildren();
        EyesPicker = null;

        if (_markingsModel is null)
            return;

        // Bucket markings by Category. Each bucket records the
        // (organ, layer, group, marking-set) needed for selection.
        var buckets = new Dictionary<string, MythosCategoryBucket>();

        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            if (!_markingsModel.OrganProfileData.TryGetValue(organ, out var organProfile))
                continue;

            foreach (var layer in organData.Layers)
            {
                var allMarkings = _markingsModel.EnforceGroupAndSexRestrictions
                    ? _marking.MarkingsByLayerAndGroupAndSex(layer, organData.Group, organProfile.Sex)
                    : _marking.MarkingsByLayer(layer);

                foreach (var (id, proto) in allMarkings)
                {
                    var category = proto.FeatureCategory();
                    if (!buckets.TryGetValue(category, out var bucket))
                    {
                        bucket = new MythosCategoryBucket(category, organ, layer, organData.Group);
                        buckets[category] = bucket;
                    }
                    bucket.Markings[id] = proto;
                }
            }
        }

        var ordered = buckets.Values
            .OrderBy(b => OvCategoryIndex(b.Category))
            .ThenBy(b => b.Category)
            .ToList();

        var i = 0;
        var injectEyes = IsMythosSpecies?.Invoke() ?? false;

        // Inject the Eyes tab synthetic-first so it lands at the top of
        // the OV-ordered tab list. Eye color isn't a MarkingPrototype so
        // there's no bucket for it; the Mythos species chargen flow
        // wants Eyes as the first feature tab regardless.
        if (injectEyes)
        {
            EyesPicker = new MythosEyesPicker();
            FeatureTabs.AddChild(EyesPicker);
            FeatureTabs.SetTabTitle(i, GetCategoryTitle("Eyes"));
            i++;
        }

        var erpAllowed = _cfg.GetCVar(CCVars.MythosChargenErpFeatures);

        foreach (var bucket in ordered)
        {
            if (bucket.Markings.Count == 0)
                continue;
            if (!erpAllowed && ErpCategories.Contains(bucket.Category))
                continue;

            var tab = new MythosCategoryPicker(_markingsModel, bucket);
            FeatureTabs.AddChild(tab);
            FeatureTabs.SetTabTitle(i, GetCategoryTitle(bucket.Category));
            i++;
        }

        FeatureTabs.TabsVisible = i > 1;
        if (i > 0)
            FeatureTabs.CurrentTab = 0;

        FeaturesRebuilt?.Invoke();
    }

    private static int OvCategoryIndex(string category)
    {
        for (var i = 0; i < OvCategoryOrder.Length; i++)
            if (OvCategoryOrder[i] == category)
                return i;
        return OvCategoryOrder.Length;
    }

    private static string GetCategoryTitle(string category)
    {
        if (Loc.TryGetString($"mythos-feature-category-{category}", out var localized))
            return localized;
        return category;
    }
}

/// <summary>
/// Backing data for one Features tab: which markings live in this
/// category and the (organ, layer, group) tuple that selection /
/// color updates need to flow through.
/// </summary>
public sealed class MythosCategoryBucket
{
    public string Category { get; }
    public ProtoId<OrganCategoryPrototype> Organ { get; }
    public HumanoidVisualLayers Layer { get; }
    public ProtoId<MarkingsGroupPrototype> Group { get; }
    public Dictionary<string, MarkingPrototype> Markings { get; } = new();

    public MythosCategoryBucket(
        string category,
        ProtoId<OrganCategoryPrototype> organ,
        HumanoidVisualLayers layer,
        ProtoId<MarkingsGroupPrototype> group)
    {
        Category = category;
        Organ = organ;
        Layer = layer;
        Group = group;
    }
}
