using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mythos.UserInterface.Systems.Location.Widgets;

// Mythos: Top-right HUD pill showing in-world time, current region, and moon phase glyph.
[GenerateTypedNameReferences]
public sealed partial class LocationTimeWidget : UIWidget
{
    public LocationTimeWidget()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetLocation(string time, string region, string moonGlyph)
    {
        TimeLabel.Text = time;
        RegionLabel.Text = region;
        MoonGlyph.Text = moonGlyph;
    }
}
