using Content.Client._Mythos.UserInterface.Systems.Character.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mythos.UserInterface.Systems.Character.Widgets;

// Mythos: Left sidebar content for the V2 HUD - portrait + 19-slot equipment paper-doll.
// Mounted inside MythosEquipmentPanel which provides the chrome (background +
// collapse button + side anchoring); this widget is just the content.
[GenerateTypedNameReferences]
public sealed partial class CharacterPanel : UIWidget
{
    public CharacterPanel()
    {
        RobustXamlLoader.Load(this);
    }

    public PortraitControl PortraitControl => Portrait;
    public EquipmentSlotsControl Equipment => EquipmentSlots;
}
